server:
  tomcat:
    protocol-header: x-forwarded-proto
    uri-encoding: UTF-8
  port: 28090
  max-http-header-size: 1MB

spring:
  main:
    allow-bean-definition-overriding: true # bean 덮어쓰는 설정
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create # 실제 사용 시 validate 값 사용
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    view:
      suffix: .html
    async:
      request-timeout: 600000
    pathmatch:
      matching-strategy: ant_path_matcher

# Oauth 관련 값 추가 필요
security:
  oauth2:
    client:
      client-id: client-id
      client-secret: client-secret
      access-token-uri: token-uri
    resource:
      token-info-uri: token-uri
      user-info-uri: user-uri
tbase:
  oauth2:
    resources:
      revoke-token-uri: revoke-token-uri
      callback-url: callback-url

skel:
  datasource:
    master:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:masterdb;MODE=MySQL;
      username: sa
      password:

logging:
  config: config/logback-spring.xml

# 추가 프로필 사용 시
--- #local
spring:
  config:
    activate:
      on-profile: local